"""Inline the poster's fonts as static instances, so the PDF embeds them.

Chrome's printToPDF wrote the body text as Type3 glyph programs instead of
embedding IBM Plex Sans. The text prints, but Type3 is what a print shop's
preflight is most likely to reject, and it is not reliably searchable.

The cause is not the URL: Google Fonts serves IBM Plex Sans as a **variable**
font (Mono is static, which is why Mono embedded and Sans did not), and Chrome
cannot embed a variable instance into a PDF. So each weight is pinned to a
static instance here before it is inlined. That also makes the poster render
identically on a machine with no network.

    python poster/embed_fonts.py                       # the defaults
    python poster/embed_fonts.py "Bodoni Moda:wght@400;700" "Inter:wght@400;600"
"""
from __future__ import annotations

import base64
import io
import re
import urllib.request
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

HERE = Path(__file__).resolve().parent
OUT = HERE / "fonts.css"

import sys

DEFAULT_FAMILIES = (
    "IBM+Plex+Sans:wght@400;500;600;700",
    "IBM+Plex+Mono:wght@400;500;600",
)
# Families may be given on the command line, so a change of typeface does not
# need a change of file: "Bodoni Moda:wght@400;700" and so on.
FAMILIES = tuple(a.replace(" ", "+") for a in sys.argv[1:]) or DEFAULT_FAMILIES
# A browser UA is what makes Google Fonts serve woff2 rather than ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def as_static(raw: bytes, weight: int) -> tuple[bytes, bool]:
    """Pin a variable face to one weight; return the bytes and whether it moved.

    A variable font is the reason Chrome falls back to Type3, so anything with
    an `fvar` table is instantiated at the weight this face is declared for.
    Static faces are passed straight back.
    """
    font = TTFont(io.BytesIO(raw), fontNumber=0)
    if "fvar" not in font:
        return raw, False
    axes = {axis.axisTag: weight for axis in font["fvar"].axes if axis.axisTag == "wght"}
    # Renamed to the pinned weight, so preflight does not see four
    # different faces all calling themselves Regular.
    instancer.instantiateVariableFont(font, axes, inplace=True,
                                      updateFontNames=True)
    font.flavor = "woff2"
    buffer = io.BytesIO()
    font.save(buffer)
    return buffer.getvalue(), True


def main() -> None:
    url = ("https://fonts.googleapis.com/css2?"
           + "&".join(f"family={family}" for family in FAMILIES)
           + "&display=swap")
    css = fetch(url).decode("utf-8")

    # Only the latin blocks are wanted; the poster is English throughout, and
    # pulling every subset would quadruple the file for nothing.
    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css)
    kept: list[str] = []
    seen: set[tuple[str, str, str]] = set()
    for subset, block in blocks:
        if subset not in ("latin", "latin-ext"):
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = (re.search(r"font-style:\s*(\w+)", block) or [None, "normal"])[1]
        key = (family, weight, subset)
        if key in seen:
            continue
        seen.add(key)
        href = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not href:
            continue
        static, pinned = as_static(fetch(href.group(1)), int(weight))
        data = base64.b64encode(static).decode("ascii")
        kept.append(
            f"@font-face{{font-family:'{family}';font-style:{style};"
            f"font-weight:{weight};font-display:block;"
            f"src:url(data:font/woff2;base64,{data}) format('woff2');}}")
        print(f"  {family:<16} {weight:<4} {subset:<10} {len(data)/1024:6.0f} KB"
              f"{'   (pinned from variable)' if pinned else ''}")

    header = ("/* Generated by poster/embed_fonts.py — IBM Plex, SIL Open Font License.\n"
              "   Inlined so the PDF embeds real fonts instead of Type3 glyph programs. */\n")
    OUT.write_text(header + "\n".join(kept) + "\n", encoding="utf-8")
    print(f"\n  {OUT.name}  {OUT.stat().st_size/1024:.0f} KB  ({len(kept)} faces)")


if __name__ == "__main__":
    main()
